#!/usr/bin/env bash
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
printf '  \033[1m⚡ zap\033[0m  ·  \033[1mNever get walled off mid-task\033[0m\n'
printf '\n'
printf '  Claude Max and ChatGPT Codex both meter you on a rolling\n'
printf '  5-hour window. You find out it ran out when your session\n'
printf '  just... stops answering.\n'
printf '\n'
printf '  \033[1mzap watches both windows live\033[0m — right in the sidebar —\n'
printf '  and warns you before you hit the wall, not after.\n'
printf '\n'
printf '  \033[38;5;220m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m\n'
printf '\n'
